#!/bin/bash
# Author: Luke Swaby lds20@ic.ac.uk
# Script: CountLines.sh
# Desc: More playing around with variables
# Arguments: 1
# Date: Oct 2020

if if (( $# != 1 )) 
then
	echo "This script requires 1 argument (a file path). You have provided $#."
	exit
fi

NumLines=$(wc -l < $1 | tr -d '[:space:]') #Strip whitespace generated by wc -l
Filename=${1##*/}
echo "The file '$Filename' contains $NumLines lines."